#!/bin/bash
# genimage exec-pre hook for the Buddy3D image layer.
#
# genimage(1) invokes this once per partition image as `setup.sh <LABEL>` with
# IMAGEMOUNTPATH set to the mounted partition image (see rpi-image-gen v2.8.0
# image/mbr/simple_dual/setup.sh, which this follows). It writes PARTUUID-based
# boot configuration — never /dev/mmcblk0pN — and seeds the durable layout.
set -eu

LABEL="${1:?partition label required}"

# The kernel derives MBR PARTUUIDs as <disk-signature>-NN.
sig="${IGconf_image_disksig#0x}"
boot_pu="${sig}-01"
root_pu="${sig}-02"
persist_pu="${sig}-03"

case "$LABEL" in
   BOOT)
      # cmdline.txt lives on the FAT boot partition, populated by genimage
      # from the rootfs /boot/firmware directory (mountpoint = "/boot/firmware").
      cmdline="$IMAGEMOUNTPATH/cmdline.txt"
      sed -i "s|root=[^ ]*|root=PARTUUID=$root_pu|" "$cmdline"
      # overlayroot(8) mounts ROOT read-only and layers a tmpfs upper (AC-10).
      if ! grep -q 'overlayroot=' "$cmdline"; then
         sed -i "s|\$| overlayroot=tmpfs|" "$cmdline"
      fi
      ;;
   ROOT)
      # PARTUUID-based fstab. ROOT is the immutable overlay lower; PERSIST is
      # mounted directly at /data and is never part of the volatile overlay.
      cat > "$IMAGEMOUNTPATH/etc/fstab" << EOF
# Generated by image/layer/setup.sh. PARTUUIDs derive from the fixed MBR disk
# signature ${IGconf_image_disksig}; never hard-code /dev/mmcblk0pN.
PARTUUID=$root_pu     /               ext4  ro,noatime,commit=30               0 1
PARTUUID=$boot_pu     /boot/firmware  vfat  defaults,rw,noatime,errors=remount-ro  0 2
PARTUUID=$persist_pu  /data           ext4  defaults,noatime,errors=remount-ro     0 2
EOF
      # Persistent overlayroot configuration: tmpfs upper, no recursion.
      install -d -m 0755 "$IMAGEMOUNTPATH/etc"
      printf 'overlayroot="tmpfs:recurse=0"\n' > "$IMAGEMOUNTPATH/etc/overlayroot.conf"
      ;;
   PERSIST)
      # Seed the durable layout. persist_restore.py recreates it idempotently
      # at runtime; no device identity (state.json/identity.json) is written at
      # build time.
      install -d -m 0750 \
         "$IMAGEMOUNTPATH/prusa-cam" \
         "$IMAGEMOUNTPATH/prusa-cam/config" \
         "$IMAGEMOUNTPATH/prusa-cam/releases" \
         "$IMAGEMOUNTPATH/prusa-cam/backups" \
         "$IMAGEMOUNTPATH/network" \
         "$IMAGEMOUNTPATH/network/system-connections" \
         "$IMAGEMOUNTPATH/sdcard" \
         "$IMAGEMOUNTPATH/sdcard/timelapse"
      uid="$(awk -F: '$1=="prusa-cam"{print $3}' "${IGconf_target_path}/etc/passwd" 2>/dev/null || true)"
      gid="$(awk -F: '$1=="prusa-cam"{print $4}' "${IGconf_target_path}/etc/passwd" 2>/dev/null || true)"
      if [ -n "$uid" ] && [ -n "$gid" ]; then
         chown -R "$uid:$gid" \
            "$IMAGEMOUNTPATH/prusa-cam" \
            "$IMAGEMOUNTPATH/network" \
            "$IMAGEMOUNTPATH/sdcard"
      fi
      ;;
esac
